name: Helper

web: "[http://holyshared.github.com/Helper](http://holyshared.github.com/Helper)"

description:

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://sharedhat.com/mit-license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/Core.js"
  - "Source/Keyboard.js"

author: holyshared

category: Interface

tags: [helper, mobile]

current: 1.0

#docs: http://url_to_plugin_docs

#demo: http://url_to_plugin_demo