name: Helper

web: "[http://holyshared.github.com/Helper](http://holyshared.github.com/Helper)"

description: The helper is a library where a specific function can do in plug and play.

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://sharedhat.com/mit-license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/Helper.js"
  - "Source/Helper.Keyboard.js"
  - "Source/Helper.Swipe.js"
  - "Source/Helper.Orientation.js"

author: holyshared

category: Interface

tags: [helper, mobile]

current: 1.1

#docs: http://url_to_plugin_docs

demo: http://holyshared.github.com/Helper/